### ISSUE TITLE
Idea: Pass state to actions context

### ISSUE THREAD

**Issue by l-portet** [DJanoskova/vuex-but-for-react#11]
Another idea that would be useful to me is to access the state inside an action context.

Example:

```javascript
// store.js
const store = {
  state: { count: 0 },
  mutations: {
    SET_COUNT(state, value) {
      state.count = value;
    }
  },
  actions: {
    increment(context) { // context only contains actions and mutations
      context.mutations.SET_COUNT(context.state.count + 1);
    }
  }
}
```

Idk if it's possible though, as you mentioned the way the state is written is not really reactive.

**Comment by DJanoskova** [comment]
Hi @l-portet ,
Sorry for the late reply, I had another state management lib in progress! That one led me to using React's `useSyncExternalStore` and this allowed a complete upgrade for `vuex-but-for-react` to a `3.0.0` version that does support state in actions context 🎉
