### ISSUE TITLE
could you please update react dependency?

### ISSUE THREAD

**Issue by dwfee** [DJanoskova/vuex-but-for-react#5]
plugin depends peer react@"^16.8.0"
but current react version is now  @"17.0.2"
could you please fix this!

Thanks in advance! 
Very nice Project and I hope I can use it in my Project once updated.

**Comment by DJanoskova** [comment]
Thanks @dwfee , I'll have a look during the weekend 😊
I also had this issue when installing vuex-but-for-react, for now I just picked to ignore the warnings 😬
